### ISSUE TITLE
conflict resolution in transformation running in parallel on different nodes

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1340]
```
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO transformationcache (cache_key, header, payload) VALUES (?, ?, ?)]; ERROR: duplicate key value violates unique constraint "transformationcache_pkey"
  Detail: Key (cache_key)=(c6162048-b8a7-11eb-891e-0267a8cd5084-1-[2, 1]) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "transformationcache_pkey"
  Detail: Key (cache_key)=(c6162048-b8a7-11eb-891e-0267a8cd5084-1-[2, 1]) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)
	at org.factcast.store.pgsql.registry.transformation.cache.PgTransformationCache.put(PgTransformationCache.java:40)
	at org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl.transformIfNecessary(FactTransformerServiceImpl.java:69)
	at org.factcast.store.pgsql.registry.transformation.FactTransformersImpl.lambda$transformIfNecessary$2(FactTransformersImpl.java:57)
	at org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl.timed(RegistryMetricsImpl.java:105)
	at org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl.timed(RegistryMetricsImpl.java:118)
	at org.factcast.store.pgsql.registry.transformation.FactTransformersImpl.transformIfNecessary(FactTransformersImpl.java:54)
	at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:161)
	at org.factcast.store.pgsql.internal.PgFactStream$FactRowCallbackHandler.processRow(PgFactStream.java:185)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1696)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:723)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:773)
	at org.factcast.store.pgsql.internal.PgSynchronizedQuery.lambda$run$0(PgSynchronizedQuery.java:86)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.factcast.store.pgsql.internal.PgSynchronizedQuery.run(PgSynchronizedQuery.java:83)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.runTarget(CondensedQueryExecutor.java:97)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.trigger(CondensedQueryExecutor.java:68)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.onEvent(CondensedQueryExecutor.java:91)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "transformationcache_pkey"
  Detail: Key (cache_key)=(c6162048-b8a7-11eb-891e-0267a8cd5084-1-[2, 1]) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy117.executeUpdate(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
```

**Comment by uweschaefer** [comment]
needs to be backported to 0.3.8 line
