### ISSUE TITLE
remove HalfClosed Exception handling

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1412]
**Describe the bug**
As is seems to swallow exceptions that should have been transported to the client:

`Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@`

for instance:

`org.factcast.core.FactValidationException: 
FactValidationError(level=error, message=string "2021-07-07T17:30:31.02+02:00[Europe/Paris]" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z])
	at org.factcast.store.pgsql.registry.validation.FactValidationAspect.validate(FactValidationAspect.java:56)
	at org.factcast.store.pgsql.registry.validation.FactValidationAspect.interceptPublish(FactValidationAspect.java:43)`

**Comment by uweschaefer** [comment]
closed by #1458
