### ISSUE TITLE
Facts with same id are not reported as duplicate to grpc client

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#149]
_From @BernhardBln on 2018-10-19 13:30:13 +0000 UTC_

**Describe the bug**
It seems that (at least not always) duplicate facts (with same id) published with the server are rejected by the server as duplicates.
The server writes an error in its log, that it was duplicate, but the client just returns without an exception.

**FactCast Server/Client Version**
0.0.16-SNAPSHOT for both client and server, the snapshot from this branch: https://github.com/Mercateo/factcast/pull/148

**To Reproduce**
Use grpc cli from https://github.com/Mercateo/factcast/pull/148 and publish the same fact twice.

**Expected behavior**
An exception should be thrown, I guess?

_Copied from original issue: Mercateo/factcast#149_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-10-19 13:45:41 +0000 UTC_

inMem Store pgsql Store or both?

**Comment by uweschaefer** [comment]
_From @BernhardBln on 2018-10-19 14:02:41 +0000 UTC_

Yeah, inMem store

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-10-19 14:03:41 +0000 UTC_

GRPC Server impl correctly propagates exception to client:

`2018-10-19 15:58:38.782  INFO 31217 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-10-19 15:58:39.057  WARN 31217 --- [           main] org.factcast.client.grpc.GrpcFactStore   : failed to publish 1 facts: {}

io.grpc.StatusRuntimeException: INTERNAL: PreparedStatementCallback; SQL [INSERT INTO fact(header,payload) VALUES (cast(? as jsonb),cast (? as jsonb))]; ERROR: duplicate key value violates unique constraint "idx_fact_unique_id"
  Detail: Key ((header -> 'id'::text))=("7834c2a1-5544-422c-a3de-043c65d34c6f") already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_fact_unique_id"
  Detail: Key ((header -> 'id'::text))=("7834c2a1-5544-422c-a3de-043c65d34c6f") already exists.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221) ~[grpc-stub-1.12.0.jar:1.12.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202) ~[grpc-stub-1.12.0.jar:1.12.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131) ~[grpc-stub-1.12.0.jar:1.12.0]
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$RemoteFactStoreBlockingStub.publish(RemoteFactStoreGrpc.java:274) ~[factcast-grpc-api-0.0.17.jar:0.0.17]
	at org.factcast.client.grpc.GrpcFactStore.publish(GrpcFactStore.java:123) ~[factcast-client-grpc-0.0.17.jar:0.0.17]
	at org.factcast.core.DefaultFactCast.publish(DefaultFactCast.java:74) [factcast-core-0.0.17.jar:0.0.17]
	at org.factcast.core.FactCast.publish(FactCast.java:43) [factcast-core-0.0.17.jar:0.0.17]
	at com.mercateo.content.distribution.factcast.TestConversation.run(TestConversation.java:21) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.mercateo.content.distribution.factcast.FCClient.main(FCClient.java:24) [classes/:na]
`

however, on void methods this should probably throw an exception clientside.

Responsible code: GrpsFactStore::public

` } catch (Exception e) {
            log.warn("failed to publish {} facts: {}", factsToPublish.size(), e);
        }`
