### ISSUE TITLE
Have descriptive error message when publishing fails due to duplicate id

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1681]
Under some heavy load situations it seems like that we're able to publish events even if the FC returns an exception to the client.

For example, on the client side we get:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: unavailable
```

while the FC logs
```
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall.close(TracingServerInterceptor.java:98)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
	at net.devh.boot.grpc.server.metric.MetricCollectingServerCall.close(MetricCollectingServerCall.java:60)
	at org.factcast.server.grpc.GrpcServerExceptionInterceptor$ExceptionHandlingServerCallListener.handleException(GrpcServerExceptionInterceptor.java:104)
	at org.factcast.server.grpc.GrpcServerExceptionInterceptor$ExceptionHandlingServerCallListener.onCancel(GrpcServerExceptionInterceptor.java:63)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.AbstractAuthenticatingServerCallListener.onCancel(AbstractAuthenticatingServerCallListener.java:117)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.metric.MetricCollectingServerCallListener.onCancel(MetricCollectingServerCallListener.java:76)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall$TracingServerCallListener.onCancel(TracingServerInterceptor.java:143)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:861)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It the client retries to publish the event it will get something like 
```
org.factcast.core.store.RetryableException: io.grpc.StatusRuntimeException: UNKNOWN
````

while the server logs 
```
ava.lang.IllegalArgumentException: PreparedStatementCallback; SQL [INSERT INTO fact(header,payload) VALUES (cast(? as jsonb),cast (? as jsonb))]; ERROR: duplicate key value violates unique constraint "idx_fact_unique_uuid"
  Detail: Key (((header ->> 'id'::text)::uuid))=(7b8dda37-4ddd-45ed-a3cd-0710c6c5d9f5) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_fact_unique_uuid"
  Detail: Key (((header ->> 'id'::text)::uuid))=(7b8dda37-4ddd-45ed-a3cd-0710c6c5d9f5) already exists.
```

The event is already present.

It feels like this related to heavy load on the db (the insert takes a lot of time). We should investigate this issue at some point.

**Comment by uweschaefer** [comment]
While the problem can technically not be solved (commit before answer is sent), the error-msg of publishing duplicates should be transported to the client in a more descriptive way.

**Comment by uweschaefer** [comment]
we decided to have a configurable switch that makes the server just swallow duplications. this might be tricky, as in case of batches, you'd need to fall back to publishing one by one in order to find the one to swallow.
