### ISSUE TITLE
Client gRPC exception after was persisted 

### ISSUE THREAD

**Issue by samba2** [factcast/factcast#1682]
**Describe the bug**
When running FactCast under high load, occasionally (currently roughly every 5 minutes) the client receives the following exception:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: unavailable
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$RemoteFactStoreBlockingStub.publish(RemoteFactStoreGrpc.java:994)
	at org.factcast.client.grpc.GrpcFactStore.lambda$publish$0(GrpcFactStore.java:163)
	at org.factcast.client.grpc.GrpcFactStore.runAndHandle(GrpcFactStore.java:172)
	at org.factcast.client.grpc.GrpcFactStore.publish(GrpcFactStore.java:156)
	at org.factcast.core.DefaultFactCast.publish(DefaultFactCast.java:48)
	at org.factcast.core.FactCast.publish(FactCast.java:42)
	at my.service.EventPublisher.publish(EventPublisher.kt:27)
	at my.service.EventPickupService$fetch$2.invoke(EventPickupService.kt:54)
	at my.service.EventPickupService$fetch$2.invoke(EventPickupService.kt:53)
	at my.service.Metrics.timedEventProcessing$lambda-0(Metrics.kt:20)
	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160)
	at my.service.Metrics.timedEventProcessing(Metrics.kt:20)
	at my.service.EventPickupService.fetch(EventPickupService.kt:53)
	at my.service.EventPickupService$$FastClassBySpringCGLIB$$d9312246.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at com.github.alturkovic.lock.advice.LockMethodInterceptor.executeLockedMethod(LockMethodInterceptor.java:76)
	at com.github.alturkovic.lock.advice.LockMethodInterceptor.invoke(LockMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at my.service.EventPickupService$$EnhancerBySpringCGLIB$$c2ab1880.fetch(<generated>)
	at my.service.PgListener.listen$lambda-2(PgListener.kt:47)
	at java.lang.Thread.run(Thread.java:748)
```

On FactCast server log side, this exception is logged:
```
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@436b331bjava.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall.close(TracingServerInterceptor.java:98)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
	at net.devh.boot.grpc.server.metric.MetricCollectingServerCall.close(MetricCollectingServerCall.java:60)
	at org.factcast.server.grpc.GrpcServerExceptionInterceptor$ExceptionHandlingServerCallListener.handleException(GrpcServerExceptionInterceptor.java:104)
	at org.factcast.server.grpc.GrpcServerExceptionInterceptor$ExceptionHandlingServerCallListener.onCancel(GrpcServerExceptionInterceptor.java:63)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.AbstractAuthenticatingServerCallListener.onCancel(AbstractAuthenticatingServerCallListener.java:117)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.metric.MetricCollectingServerCallListener.onCancel(MetricCollectingServerCallListener.java:76)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
	at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
	at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall$TracingServerCallListener.onCancel(TracingServerInterceptor.java:143)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:861)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

When retrying to publish the fact (2nd attempt), the client receives this exception:
```
org.factcast.core.store.RetryableException: io.grpc.StatusRuntimeException: UNKNOWN
```

On the server side, this is logged:

```
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@355682a5java.lang.IllegalArgumentException: PreparedStatementCallback; SQL [INSERT INTO fact(header,payload) VALUES (cast(? as jsonb),cast (? as jsonb))]; ERROR: duplicate key value violates unique constraint "idx_fact_unique_uuid"
  Detail: Key (((header ->> 'id'::text)::uuid))=(c4e01419-9199-4262-a84d-b354cdc61694) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_fact_unique_uuid"
  Detail: Key (((header ->> 'id'::text)::uuid))=(c4e01419-9199-4262-a84d-b354cdc61694) already exists.
	at org.factcast.store.internal.PgFactStore.lambda$publish$2(PgFactStore.java:146)
	at org.factcast.store.internal.PgMetrics.time(PgMetrics.java:60)
	at org.factcast.store.internal.PgFactStore.publish(PgFactStore.java:125)
	at org.factcast.store.internal.PgFactStore$$FastClassBySpringCGLIB$$61e94cd3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.factcast.store.registry.validation.FactValidationAspect.interceptPublish(FactValidationAspect.java:45)
	at jdk.internal.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.factcast.store.internal.PgFactStore$$EnhancerBySpringCGLIB$$ab469f30.publish(<generated>)
	at org.factcast.server.grpc.FactStoreGrpcService.publish(FactStoreGrpcService.java:147)
	at org.factcast.server.grpc.FactStoreGrpcService$$FastClassBySpringCGLIB$$10df9000.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.factcast.server.grpc.FactStoreGrpcService$$EnhancerBySpringCGLIB$$a64d9ae1.publish(<generated>)
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$MethodHandlers.invoke(RemoteFactStoreGrpc.java:1284)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at org.factcast.server.grpc.GrpcServerExceptionInterceptor$ExceptionHandlingServerCallListener.onHalfClose(GrpcServerExceptionInterceptor.java:91)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.AbstractAuthenticatingServerCallListener.onHalfClose(AbstractAuthenticatingServerCallListener.java:103)
	at net.devh.boot.grpc.server.security.interceptors.DefaultAuthenticatingServerInterceptor$AuthenticatingServerCallListener.onHalfClose(DefaultAuthenticatingServerInterceptor.java:166)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.ExceptionTranslatingServerInterceptor$ExceptionTranslatorServerCallListener.onHalfClose(ExceptionTranslatingServerInterceptor.java:124)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall$TracingServerCallListener.onHalfClose(TracingServerInterceptor.java:133)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Looking at these logs, I suspect the following to go wrong:
- when under high load, a fact is written to disk but some gRPC exception follows after that write
- now the "publish" was actually successful but unfortunately the client receives an exception
- a subsequent publish of the same fact fails as it is already stored in the `fact` table

**FactCast Server/Client Version**
server: 0.4.3
client: 0.4.3

**To Reproduce**
- try to publish many facts at once to FC (keyword *pickup-service*)

**Expected behavior**
- a "publish" should ideally just work ;-) or fail with a meaningful exception
- the current behaviour "successful fact persistence + exception" is not desired

**Comment by BernhardBln** [comment]
Not sure if it is connected, just mentioning it here: https://github.com/grpc/grpc-java/issues/3746

**Comment by samba2** [comment]
to add on the issue description. the issue appears quite exactly every 5 minutes

**Comment by uweschaefer** [comment]
this was an infrastructure problem.
