### ISSUE TITLE
Publishing at high rates throws

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#17]
_From @otbe on 2017-05-11 11:43:16 +0000 UTC_

Hi,

I try to "cast facts" every 1ms which gives me:
```
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: sorry, too many clients already
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:289) ~[spring-jdbc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447) ~[spring-tx-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277) ~[spring-tx-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.factcast.store.pgsql.internal.PGFactStore$$EnhancerBySpringCGLIB$$5ca53cc3.publish(<generated>) ~[factcast-store-pgsql-0.0.1-SNAPSHOT.jar!/:na]
	at org.factcast.server.grpc.FactStoreGrpcService.publish(FactStoreGrpcService.java:75) ~[factcast-server-grpc-0.0.1-SNAPSHOT.jar!/:na]
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$MethodHandlers.invoke(RemoteFactStoreGrpc.java:282) [factcast-grpc-api-0.0.1-SNAPSHOT.jar!/:na]
	at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:148) [grpc-stub-1.2.0.jar!/:1.2.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:266) [grpc-core-1.2.0.jar!/:1.2.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:586) [grpc-core-1.2.0.jar!/:1.2.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52) [grpc-core-1.2.0.jar!/:1.2.0]
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152) [grpc-core-1.2.0.jar!/:1.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: com.impossibl.postgres.jdbc.PGSQLSimpleException: Connection Error: sorry, too many clients already
```

Client code looks like this:
```javascript
const protoDescriptor = grpc.load('./FactStore.proto');
const RemoteFactStore = protoDescriptor.org.factcast.grpc.api.gen.RemoteFactStore;

const store = new RemoteFactStore('localhost:9090', grpc.credentials.createInsecure());

setInterval(() =>
  store.publish([{
    header: JSON.stringify({
      id: uuidV4(),
      ns: 'my-cool-fact-ns'
    }),
    payload: JSON.stringify({
      foo: Date.now()
    })
  }], (err, feature) => {
    if (err) {
      console.log(err)
    }
  }), 1);
```
Note: I dont get an error object passed in my callback. :/

Thanks! 👍 

_Copied from original issue: Mercateo/factcast#17_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2017-05-11 13:55:35 +0000 UTC_

Connection pooling issue. Working on it.

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2017-05-11 13:57:25 +0000 UTC_

you should recieve an error, though

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2017-05-11 16:27:56 +0000 UTC_

fixed

**Comment by uweschaefer** [comment]
_From @otbe on 2017-05-11 16:31:20 +0000 UTC_

Thanks!
