### ISSUE TITLE
Retry on networking errors during refreshing from schemareg and reduce log level to tmp errors to WARN level

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1725]
We use S3 to server the registry, which pretty often is not avail:

```
org.factcast.store.registry.SchemaRegistryUnavailableException: org.factcast.store.registry.SchemaRegistryUnavailableException: Status code 500: Internal Server Error while requesting http://something.s3-website.some-region.amazonaws.com/registry/index.json
	at org.factcast.store.registry.http.HttpIndexFetcher.fetchIndex(HttpIndexFetcher.java:111)
	at org.factcast.store.registry.AbstractSchemaRegistry.lambda$refresh$0(AbstractSchemaRegistry.java:127)
	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160)
	at org.factcast.store.registry.metrics.RegistryMetricsImpl.timed(RegistryMetricsImpl.java:51)
	at org.factcast.store.registry.metrics.RegistryMetricsImpl.timed(RegistryMetricsImpl.java:56)
	at org.factcast.store.registry.AbstractSchemaRegistry.refresh(AbstractSchemaRegistry.java:123)
	at org.factcast.store.registry.ScheduledRegistryRefresher.refresh(ScheduledRegistryRefresher.java:40)
```

It might be a good change to reduce log level to WARN here.

**Comment by uweschaefer** [comment]
Rather than just decreasing the loglevel, we agreed to have a retry mechanism with back-off.
