### ISSUE TITLE
Errors during scheduled flush of TransformationCache 

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#2158]
Recently we saw errors in our fc logs that might indicate a problem.

```
PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 83,791 parameters
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328)
	at org.factcast.store.registry.transformation.cache.PgTransformationCache.insertBufferedAccesses(PgTransformationCache.java:214)
	at org.factcast.store.registry.transformation.cache.PgTransformationCache.flush(PgTransformationCache.java:176)
	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at io.opentelemetry.javaagent.instrumentation.spring.scheduling.SpringSchedulingRunnableWrapper.run(SpringSchedulingRunnableWrapper.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 83,791 parameters
	at org.postgresql.jdbc.PgPreparedStatement.<init>(PgPreparedStatement.java:102)
	at org.postgresql.jdbc.PgPreparedStatement.<init>(PgPreparedStatement.java:88)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1325)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1784)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:454)
	at jdk.internal.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:131)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at jdk.proxy3/jdk.proxy3.$Proxy137.prepareStatement(Unknown Source)
	at org.springframework.jdbc.core.PreparedStatementCreatorFactory$PreparedStatementCreatorImpl.createPreparedStatement(PreparedStatementCreatorFactory.java:235)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	... 17 common frames omitted

```

What I get from the code, I would say this shouldn't be possible at all because theres an upper limit

**Comment by otbe** [comment]
While looking at the code I think I found the root cause.

[In this line](https://github.com/factcast/factcast/blob/8a8cef118e0879c00096dd8f4c394e75aab3224a/factcast-store/src/main/java/org/factcast/store/registry/transformation/cache/PgTransformationCache.java#L133) we put an arbitrary number of read facts into the buffer and do not flush (ifNecessary) afterwards which then can lead to a situation where we have a huge number of facts in the buffer.

What do you think @bresciamattia @uweschaefer ?

**Comment by uweschaefer** [comment]
yep. we'd need to either partition on the flush side, or partition and flush at the findAll method.

**Comment by uweschaefer** [comment]
flushIfNecessary might not be enough, as the input collection is unbounded.

**Comment by otbe** [comment]
Added some partitioning based on best guess size :D
