### ISSUE TITLE
Connection issue caused thousands of logs

### ISSUE THREAD

**Issue by StephanPraetsch** [factcast/factcast#2170]
Hi there,

maybe this is already fixed in a newer version, but still wanted to mention. Maybe it's still an issue.

**Describe the bug**
Connection issue caused thousands of logs: 19:40-1945 and 20:37-20:40 produced more than 16000 logs
![image](https://user-images.githubusercontent.com/9827763/196401690-1d5536cf-8f4a-4a46-b752-9ac8aea0da16.png)

**FactCast Server/Client Version**
0.3.8

**To Reproduce**
Unfortunately no clue. Run FactCast and shutdown its database for 5 min? Seems like AWS RDS wasn't available for a period.

**Expected behavior**
Not a spam of thousands of logs.

**Additional context**

Stacktrace
```
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:612)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.factcast.store.pgsql.internal.PgFactStore.lambda$getStateFor$9(PgFactStore.java:259)
	at org.factcast.store.pgsql.internal.PgMetrics.time(PgMetrics.java:74)
	at org.factcast.store.pgsql.internal.PgFactStore.getStateFor(PgFactStore.java:238)
	at org.factcast.core.store.AbstractFactStore.stateFor(AbstractFactStore.java:65)
	at org.factcast.core.store.AbstractFactStore$$FastClassBySpringCGLIB$$8eef5e70.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.factcast.store.pgsql.internal.PgFactStore$$EnhancerBySpringCGLIB$$68378ae6.stateFor(<generated>)
	at org.factcast.server.grpc.FactStoreGrpcService.stateForSpecsJson(FactStoreGrpcService.java:387)
	at org.factcast.server.grpc.FactStoreGrpcService$$FastClassBySpringCGLIB$$10df9000.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.factcast.server.grpc.FactStoreGrpcService$$EnhancerBySpringCGLIB$$cca3e9b1.stateForSpecsJson(<generated>)
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$MethodHandlers.invoke(RemoteFactStoreGrpc.java:1336)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at org.factcast.server.grpc.GrpcExceptionInterceptor$ExceptionHandlingServerCallListener.onHalfClose(GrpcExceptionInterceptor.java:55)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.AbstractAuthenticatingServerCallListener.onHalfClose(AbstractAuthenticatingServerCallListener.java:103)
	at net.devh.boot.grpc.server.security.interceptors.DefaultAuthenticatingServerInterceptor$AuthenticatingServerCallListener.onHalfClose(DefaultAuthenticatingServerInterceptor.java:166)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.ExceptionTranslatingServerInterceptor$ExceptionTranslatorServerCallListener.onHalfClose(ExceptionTranslatingServerInterceptor.java:124)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:405)
	at org.postgresql.Driver.connect(Driver.java:263)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:319)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:671)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	... 45 common frames omitted
```

**Comment by uweschaefer** [comment]
Hi Stefan,

Thanks for the report. Yes, the resilience behavior of the client lib has changed very significantly. I'd encourage you to move to the latest version.
For the Server, it looks like as if you're generating an execption for every call from a client. (Call comes from "stateFor(AbstractFactStore.java:65)"). The the server tries to get a new connection from the CP, which fails as the database does not provide new connections.

I feel like it is correct behavior here to log the exception and not swallow it because 
* when to start/stop swallowing anyway?
* people might use alarming/dashboards on top of logs [we do]. How to distinguish an error condition from a healthy service, if we swallow exceptions.

Alternatively, the actuator for the CP should have been DOWN, and i'd expect the service to be shot down, when an actuator is DOWN for a long time. What i am trying to say is, the runtime environment (AWS here, i suppose) should be in charge of stopping and restarting the server (or escalating) if the database is not working as expected, instead of keeping the service UP and wait for a miracle self-healing while swallowing exceptions.

Makes sense?

PS: Dunno what happened to your RDS, but please keep in mind that RDS provides a limited number of connections proportional to the instance size. It might be that either you deployed RDS on a too small instance, or the number of connections per FactCast should be reduced.

**Comment by uweschaefer** [comment]
https://docs.factcast.org/setup/grpc-client/grpc-resilience/

**Comment by uweschaefer** [comment]
especially



factcast.grpc.client.resilience.enabled | Enables resilience mode for subscriptions. If enabled, subscriptions that fail due to networking errors will be transparently resubscribed. (since 0.5.5) | true | false
-- | -- | -- | --
factcast.grpc.client.resilience.window | Defines the window in which a maximum of retries is defined. (since 0.5.5) | PT30S (30 seconds) | PT2M (2 Minutes)
factcast.grpc.client.resilience.attempts | Defines the maximum number of attempts that will be done (within a time window defined by resilience.window) before failing and escalating the last exception to the application. (since 0.5.5) | 10 | 25
factcast.grpc.client.resilience.interval | Defines the wait time between two attempts. (since 0.5.5) | PT0.1S (100 millis) | PT0.5S

**Comment by StephanPraetsch** [comment]
Do I understand it correctly? For this example the factcast server logged 16k logs because of 16k client requests?

We do check the health and would shut it down
```
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "curl -f http://localhost:8080/management/health || exit 1"
            Interval: 30
            Retries: 3
            Timeout: 5
            StartPeriod: 120
```
Or is that health check wrong?

The RDS instance is able to deal up to 210 connections. If this wasn't enough then it would be an issue in the factcast server.

**Comment by uweschaefer** [comment]
Dunno, but the stacktrace above shows a sync call to `stateFor`. Could be that in the ancient version you use, there is just a retry loop when a stateFor all fails from the client, but honestly, i don't know. WIth version 0.5.5 and above, you can control this (see above).

**Comment by StephanPraetsch** [comment]
Alright. Then we can close this issue as long as we use this ancient version. Just wanted to inform.

**Comment by uweschaefer** [comment]
Thanks, appreciated!
