### ISSUE TITLE
Consider Graal native image for CLI

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#224]
_From @uweschaefer on 2018-11-18 17:58:20 +0000 UTC_

**Is your feature request related to a problem? Please describe.**
it would be great to provide a native image to help with startup latency 

_Copied from original issue: Mercateo/factcast#224_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-24 03:00:37 +0000 UTC_

Obviously, the spring boot mechanics prevent this currently:
```
[org.factcast.client.grpc.cli.cli:4599]     analysis:  28,517.38 ms
error: unsupported features in 14 methods
Detailed message:
Error: Bytecode parsing error: java.lang.NoClassDefFoundError: org/springframework/web/context/support/GenericWebApplicationContext
Trace: 
	at parsing org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:591)
Call path from entry point to org.springframework.boot.SpringApplication.createApplicationContext(): 
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:586)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.factcast.client.grpc.cli.CLI.main(CLI.java:48)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.lang.NoClassDefFoundError: org/springframework/web/context/support/GenericWebApplicationContext
```

It should be possible to get rid of spring boot entirely in this project, so that another attempt at graal makes sense.

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-06-20 12:24:36 +0000 UTC_

postponed to 0.2

**Comment by BernhardBln** [comment]
Managed to get a binary under macos (needed to remove the `--static` param for it to work), now running into this error:

```
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Could not initialize Logback logging from classpath:logback.xml
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:168)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
        at java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at org.factcast.client.grpc.cli.CLI.main(CLI.java:50)
Caused by: ch.qos.logback.core.LogbackException: Logback XML configuration is not supported yet, see https://github.com/spring-projects-experimental/spring-native/issues/625
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:51)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:191)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:165)
        ... 23 more

```

They reference this ticket which is still open: https://github.com/spring-projects-experimental/spring-native/issues/625

Timebox is used up, but maybe this can be a starting point for further work. I started from main, not from the previous branch.

issue224-consider-graal-native-image-for-cli-
