### ISSUE TITLE
GRPC Client->Server communication regression

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#234]
_From @mweirauch on 2018-11-20 08:55:41 +0000 UTC_

**Describe the bug**

GRPC Client->Server publish(Fact) call.
Apparently we are missing some GRPC client->server integration/regression tests.

server-side
```
2018-11-20 09:50:05 [grpc-default-executor-0] INFO  o.f.server.grpc.FactStoreGrpcService - Handshake properties: {org.factcast.grpc.api.Capabilities.FACTCAST_IMPL_VERSION=0.0.30, org.factcast.grpc.api.Capabilities.CODEC_LZ4=false} 
2018-11-20 09:50:12 [grpc-default-worker-ELG-3-1] WARN  io.grpc.netty.NettyServerHandler - Exception in onHeadersRead()
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at io.grpc.internal.AbstractStream$TransportState.onStreamAllocated(AbstractStream.java:232)
	at io.grpc.internal.AbstractServerStream$TransportState.onStreamAllocated(AbstractServerStream.java:224)
	at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:438)
	at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:98)
	at io.grpc.netty.NettyServerHandler$FrameListener.onHeadersRead(NettyServerHandler.java:740)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:317)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:457)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:464)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2018-11-20 09:50:12 [grpc-default-worker-ELG-3-1] WARN  io.grpc.netty.NettyServerHandler - Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: 
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:149)
	at io.grpc.netty.NettyServerHandler.newStreamException(NettyServerHandler.java:701)
	at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:443)
	at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:98)
	at io.grpc.netty.NettyServerHandler$FrameListener.onHeadersRead(NettyServerHandler.java:740)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:317)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:457)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:464)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at io.grpc.internal.AbstractStream$TransportState.onStreamAllocated(AbstractStream.java:232)
	at io.grpc.internal.AbstractServerStream$TransportState.onStreamAllocated(AbstractServerStream.java:224)
	at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:438)
	... 30 common frames omitted
2018-11-20 09:50:12 [grpc-default-worker-ELG-3-1] WARN  io.grpc.netty.NettyServerHandler - Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:531)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:183)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
client-side
```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214) ~[grpc-stub-1.16.1.jar:1.16.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139) ~[grpc-stub-1.16.1.jar:1.16.1]
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$RemoteFactStoreBlockingStub.enumerateNamespaces(RemoteFactStoreGrpc.java:517) ~[classes/:na]
	at org.factcast.client.grpc.GrpcFactStore.enumerateNamespaces(GrpcFactStore.java:217) ~[classes/:na]
	at org.factcast.core.DefaultFactCast.enumerateNamespaces(DefaultFactCast.java:93) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:522) ~[wicket-ioc-8.1.0.jar:8.1.0]
	at com.sun.proxy.$Proxy95.enumerateNamespaces(Unknown Source) ~[na:na]
	at io.github.mweirauch.bootifulwicket.web.facts.NamespaceDataProvider.size(NamespaceDataProvider.java:31) ~[classes/:na]
	at org.apache.wicket.markup.repeater.data.DataViewBase.internalGetItemCount(DataViewBase.java:142) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractPageableView.getItemCount(AbstractPageableView.java:235) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractPageableView.getRowCount(AbstractPageableView.java:216) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractPageableView.getViewSize(AbstractPageableView.java:314) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractPageableView.getItemModels(AbstractPageableView.java:99) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:93) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.markup.repeater.AbstractPageableView.onBeforeRender(AbstractPageableView.java:115) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.Component.beforeRender(Component.java:937) ~[wicket-core-8.1.0.jar:8.1.0]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1753) ~[wicket-core-8.1.0.jar:8.1.0]
	... 59 common frames omitted
```

**FactCast Server/Client Version**
* client -> server calls
  * `0.0.25` -> `0.0.21` works
  * `0.0.30` -> `0.0.31-SNAPSHOT` broken
  * `0.0.30` -> `0.0.30` broken
  * `0.0.30` -> `0.0.21` works

_Copied from original issue: Mercateo/factcast#234_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-20 10:12:35 +0000 UTC_

yes, of courese we miss some integration tests. i was planning to use testconatiners to start a factcast to test against, but that was not pressing until now.
looks like a dependency upgrade to either io.grpc or grpc-spring-boot-starter is the culprit. i'll have a look on thursday..

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-20 13:11:12 +0000 UTC_

As it turns out, gzip compression does not seem to work as expected.

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-20 13:11:42 +0000 UTC_

i'll release a quick fix, but leave this open until there are proper integration tests

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-20 13:25:51 +0000 UTC_

@mweirauch could you recheck with master branch?

unfortunately, i am not able to re-release right now, due to:
```
[INFO] Performing remote staging...
[INFO] 
[INFO]  * Remote staging into staging profile ID "38d958e63bb2a5"
[ERROR] Remote staging finished with a failure: Internal Server Error : entity body dump follows: <nexus-error>
  <errors>
    <error>
      <id>*</id>
      <msg>Unhandled: java.io.IOException: No space left on device</msg>
    </error>
  </errors>
</nexus-error>
```

:p

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-20 15:47:12 +0000 UTC_

the capacity issue at sonatype was fixed and 0.0.31 is out of the door.
https://issues.sonatype.org/browse/OSSRH-44244

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-11-21 18:04:49 +0000 UTC_

let me know, if it worked for you.

**Comment by uweschaefer** [comment]
_From @mweirauch on 2018-11-22 09:25:26 +0000 UTC_

client 0.0.25 -> server 0.0.33-SNAPSHOT works. So I guess this has been fixed. Thank you!

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-04-14 14:18:00 +0000 UTC_

Reenabling GZIP compression if the server claims to support it.

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-04-14 14:21:55 +0000 UTC_

see #381

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-04-23 13:42:52 +0000 UTC_

done
