### ISSUE TITLE
Connection lost while subscribing

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#25]
_From @JoergAdler on 2017-05-18 07:55:14 +0000 UTC_

If one subscribes to the REST- adapter, one gets the following exception:

2017-05-18 09:43:25.369  WARN 18653 --- [:1495092505314]] o.a.tomcat.jdbc.pool.ConnectionPool      : Connection has been abandoned PooledConnection[com.impossibl.postgres.jdbc.PGConnectionImpl@260a943d]:java.lang.Exception
  at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1102)
  at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:807)
  at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:651)
  at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
  at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
  at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
  at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
  at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619)
  at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
  at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
  at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:741)
  at org.factcast.store.pgsql.internal.PGSynchronizedQuery.run(PGSynchronizedQuery.java:73)
  at org.factcast.store.pgsql.internal.PGFactStream.catchup(PGFactStream.java:131)
  at org.factcast.store.pgsql.internal.PGFactStream.catchupAndFollow(PGFactStream.java:81)
  at org.factcast.store.pgsql.internal.PGFactStream.connect(PGFactStream.java:65)
  at org.factcast.store.pgsql.internal.PGSubscriptionFactory.lambda$subscribe$1(PGSubscriptionFactory.java:38)
  at org.factcast.store.pgsql.internal.PGSubscriptionFactory$$Lambda$40/1078858524.run(Unknown Source)
  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
  at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

_Copied from original issue: Mercateo/factcast#25_

**Comment by uweschaefer** [comment]
_From @JoergAdler on 2017-05-19 11:10:20 +0000 UTC_

How to reproduce: I started the Server locally, Postgres on AWS. Started some exayples from https://github.com/Mercateo/rest-hateoas-client/tree/sse/src/test/java/com/mercateo/rest/hateoas/client/example/sse
(one time the first, 3 times the second)

Added the following lines in FactsObserver (serverside)
```
        anz++;
        System.out.println(this.hashCode() + " : " + anz + " : " + f.id());
```
Stream stopped at the serverside with

566788719 : 93990 : e2f3d666-065d-4ce3-a76c-a323deb89aae
2017-05-19 12:01:35.458  WARN 961 --- [:1495187825449]] o.a.tomcat.jdbc.pool.ConnectionPool      : Connection has been abandoned PooledConnection[com.impossibl.postgres.jdbc.PGConnectionImpl@3add5e17]:java.lang.Exception
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1102)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:807)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:651)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:741)
	at org.factcast.store.pgsql.internal.PGSynchronizedQuery.run(PGSynchronizedQuery.java:73)
	at org.factcast.store.pgsql.internal.PGFactStream.catchup(PGFactStream.java:131)
	at org.factcast.store.pgsql.internal.PGFactStream.catchupAndFollow(PGFactStream.java:81)
	at org.factcast.store.pgsql.internal.PGFactStream.connect(PGFactStream.java:65)
	at org.factcast.store.pgsql.internal.PGSubscriptionFactory.lambda$0(PGSubscriptionFactory.java:38)
	at org.factcast.store.pgsql.internal.PGSubscriptionFactory$$Lambda$80/1699972523.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2017-05-19 11:52:29 +0000 UTC_

thx

**Comment by uweschaefer** [comment]
_From @JoergAdler on 2017-05-19 12:36:30 +0000 UTC_

I changed example a little bit. now the server crashes, when you only run one example

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2017-05-23 16:48:14 +0000 UTC_

no longer reproducable, after changing to paging for catchup.
