### ISSUE TITLE
Flaky: ExceptionHandlingV4.testSubscriptionFC_transformationErrors_follow

### ISSUE THREAD

**Issue by leflamm** [factcast/factcast#2832]
```
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 53.10 s <<< FAILURE! -- in org.factcast.itests.exception.handling.ExceptionHandlingV4
[ERROR] org.factcast.itests.exception.handling.ExceptionHandlingV4.testSubscriptionFC_transformationErrors_follow -- Time elapsed: 2.425 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting value to be true but was false
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at org.factcast.itests.exception.handling.ExceptionHandlingV4.testSubscriptionFC_transformationErrors_follow(ExceptionHandlingV4.java:221)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

INFO  org.factcast.test.AbstractFactCastIntegrationTest - STDOUT: INFO  org.factcast.store.internal.query.CurrentStatementHolder - Canceling statement org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy[Proxy=978176964; Query=SELECT ser, header, payload, header->>'id' AS id, header->>'aggIds' AS aggIds, header->>'ns' AS ns, header->>'type' AS type, header->>'version' AS version FROM fact WHERE ( (1=1 AND header @> ?::jsonb AND header @> ?::jsonb) ) AND ser>? ORDER BY ser ASC; Delegate=null]
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExceptionHandlingV4.testSubscriptionFC_transformationErrors_follow:221 
Expecting value to be true but was false
[INFO] 
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by leflamm** [comment]
Test class has 4 similar assertions 
```
    assertThat(errorLatch.await(1000, TimeUnit.MILLISECONDS)).isTrue();
```
in different test cases. If I leave the timeout value at `1000` _on my machine_ at least one of them fails in 100% of all cases.

```
a=10;f=0;
for i in $(seq 1 ${a})
do 
mvn clean test-compile verify -Dit.test=ExceptionHandlingV4#testSubscriptionFC_transformationErrors_follow || f=$(($f + 1))
done
echo "result: ${f}/${a} runs with test failues"
```

* errorLatch.await(1000, MILLISECONDS): "result: 10/10 runs with test failues"
* errorLatch.await(1500, MILLISECONDS): "result: 4/10 runs with test failues"
* errorLatch.await(2000, MILLISECONDS): "result: 0/10 runs with test failues"
