### ISSUE TITLE
dynamic AWS RDS-Settings doesn't work with version 0.1.0-M1

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#408]
_From @jeremykrueger on 2019-05-06 08:47:13 +0000 UTC_

**Describe the bug**
The RDS-Autoconfiguration over the `spring-cloud-aws-jdbc`-library doesn't work correctly with the new 0.1.0-M1 version. When I enter the Spring DataSource-Properties manually and doesn't use the autoconfiguration, the Factcast-Instance connects correctly do the database.

**FactCast Server/Client Version**
FactCast Server 0.1.0-M1

**To Reproduce**
1. use `cloud.aws.rds.DATABASE.password=PASSWORD`-property

**Expected behavior**
The RDS Autoconfiguration should work correctly

**Additional context**
Exception:

```
10:23:06 ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pgConnectionSupplier' defined in class path resource [org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.class]: Unsatisfied dependency expressed through method 'pgConnectionSupplier' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.tomcat.jdbc.pool.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.factcast.Factcast.main(Factcast.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.tomcat.jdbc.pool.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1644)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1203)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted
```

_Copied from original issue: Mercateo/factcast#408_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-05-06 09:12:05 +0000 UTC_

I assume this happens inside a Spring-Boot-2.x container?

**Comment by uweschaefer** [comment]
_From @jeremykrueger on 2019-05-06 10:38:00 +0000 UTC_

yes, that's right. Currently we use Spring-Boot v2.1.1 as container

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-05-06 11:04:13 +0000 UTC_

could you add the pom.xml used to this issue, please?

**Comment by uweschaefer** [comment]
_From @jeremykrueger on 2019-05-06 12:29:03 +0000 UTC_

sure, here:
[pom.xml.zip](https://github.com/Mercateo/factcast/files/3147875/pom.xml.zip)

**Comment by uweschaefer** [comment]
_From @OOlsen on 2019-05-06 21:04:51 +0000 UTC_

```
 @Bean
    public PgConnectionSupplier pgConnectionSupplier(javax.sql.DataSource ds) {
        return new PgConnectionSupplier((org.apache.tomcat.jdbc.pool.DataSource)ds);
    }

 @Bean
    public PlatformTransactionManager txManager(javax.sql.DataSource ds) {
        return new DataSourceTransactionManager(ds);
    }
```

works. Seems like the datasource isn't registered as tomcat source.
(After i got rid if the of the ec2 meta information query with "cloud.aws.stack.auto=false")

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2019-05-07 05:38:28 +0000 UTC_

@OOlsen sure that defining a PlatformTransactionManager is necessary?

**Comment by uweschaefer** [comment]
_From @OOlsen on 2019-05-07 11:10:46 +0000 UTC_

It shouldn't be nessary for the application itself, but multiple tests are failing if we remove the PlatformTransactionManager. We should consider to move it into the test scope.
