### ISSUE TITLE
grpc client version 36 incompatible to master

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#432]
_From @OOlsen on 2019-05-21 14:17:17 +0000 UTC_

Just tested  a client with factcast-client-grpc 0.0.34 against the current Factcast server version 0.1.0-RC3-SNAPSHOT.
The client connection fails for unknown reasons, but the server logs shows following:

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "marks" (class org.factcast.core.subscription.SubscriptionRequestTO), not marked as ignorable (7 known properties: "debugInfo", "idOnly", "maxBatchDelayInMs", "startingAfter", "ephemeral", "continuous", "specs"])
 at [Source: (String)"{"maxBatchDelayInMs":0,"marks":true,"continuous":true,"ephemeral":false,"idOnly":false,"startingAfter":null,"debugInfo":"48896202-1e9a-4371-96fa-de9cc9c2b7da (Follow.request:55)","specs":[{"ns":"smoke","type":null,"aggId":null,"jsFilterScript":null,"meta":{}}]}"; line: 1, column: 36] (through reference chain: org.factcast.core.subscription.SubscriptionRequestTO["marks"])
///
2019-05-21 16:01:46 [grpc-default-executor-2] ERROR io.grpc.internal.SerializingExecutor -
        Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@7f5729d5
java.lang.reflect.UndeclaredThrowableException: null
 at org.factcast.server.grpc.FactStoreGrpcService$$EnhancerBySpringCGLIB$$dacd187.subscribe(<generated>)

Didn't had the time to go more into investigation yet.

_Copied from original issue: Mercateo/factcast#432_

**Comment by uweschaefer** [comment]
_From @OOlsen on 2019-05-21 15:14:57 +0000 UTC_

full stacktrace:

`2019-05-21 17:09:32 [grpc-default-executor-0] ERROR io.grpc.internal.SerializingExecutor -
        Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@29635608
java.lang.reflect.UndeclaredThrowableException: null
	at org.factcast.server.grpc.FactStoreGrpcService$$EnhancerBySpringCGLIB$$5a87bb3f.subscribe(<generated>)
	at org.factcast.grpc.api.gen.RemoteFactStoreGrpc$MethodHandlers.invoke(RemoteFactStoreGrpc.java:853)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.AuthenticatingServerInterceptor$AuthenticatingServerCallListener.onHalfClose(AuthenticatingServerInterceptor.java:151)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at net.devh.boot.grpc.server.security.interceptors.ExceptionTranslatingServerInterceptor$ExceptionTranslatorServerCallListener.onHalfClose(ExceptionTranslatingServerInterceptor.java:111)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:711)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "marks" (class org.factcast.core.subscription.SubscriptionRequestTO), not marked as ignorable (7 known properties: "debugInfo", "idOnly", "maxBatchDelayInMs", "startingAfter", "ephemeral", "continuous", "specs"])
 at [Source: (String)"{"maxBatchDelayInMs":0,"marks":true,"continuous":true,"ephemeral":false,"idOnly":false,"startingAfter":null,"debugInfo":"be577348-7f77-412c-9b28-c3bf469b35d3 (Follow.request:55)","specs":[{"ns":"smoke","type":null,"aggId":null,"jsFilterScript":null,"meta":{}}]}"; line: 1, column: 36] (through reference chain: org.factcast.core.subscription.SubscriptionRequestTO["marks"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1219)
	at org.factcast.core.util.FactCastJson.readValue(FactCastJson.java:71)
	at org.factcast.grpc.api.conv.ProtoConverter.fromProto(ProtoConverter.java:98)
	at org.factcast.server.grpc.FactStoreGrpcService.subscribe(FactStoreGrpcService.java:113)
	at org.factcast.server.grpc.FactStoreGrpcService$$FastClassBySpringCGLIB$$10df9000.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	... 18 common frames omitted
2019-05-21 17:09:32 [grpc-default-executor-0] ERROR io.grpc.internal.SerializingExecutor -
        Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@30771555`
