### ISSUE TITLE
Flaky test setup with circleCI

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#59]
_From @uweschaefer on 2018-04-23 17:49:25 +0000 UTC_

```
[ERROR] Please refer to /home/circleci/repo/factcast-store-pgsql/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/circleci/repo/factcast-store-pgsql && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java '-javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/circleci/repo/factcast-store-pgsql/target/jacoco.exec,excludes=**/*Configuration.*:**/*Application.*:**/*Exception.*:**/gen/*' -jar /home/circleci/repo/factcast-store-pgsql/target/surefire/surefirebooter4223028475847194638.jar /home/circleci/repo/factcast-store-pgsql/target/surefire 2018-04-23T17-41-06_450-jvmRun1 surefire3488497804929880745tmp surefire_31666178354826397868tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] org.factcast.store.pgsql.internal.PGLatestSerialFetcher0Test
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

Occasionally, a build fails with the above message.

_Copied from original issue: Mercateo/factcast#59_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-09-09 20:58:53 +0000 UTC_

hopefully resolved by avoiding embedded pgsql

**Comment by uweschaefer** [comment]
_From @mweirauch on 2018-09-10 06:49:17 +0000 UTC_

Might have also been "flaky" process handling in surefire of failsafe around 2.20. Had these issues too with a busybox build image. Resolved by adding `procps` package to busybox and updating to plugin versions 2.21+ IIRC.

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-09-10 07:06:18 +0000 UTC_

interesting, will update the plugin additionally, thx

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-09-10 11:24:11 +0000 UTC_

crap. again. upgrading failssafe to 2.21 did not fix it.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project factcast-store-pgsql: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/circleci/repo/factcast-store-pgsql/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/circleci/repo/factcast-store-pgsql && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java '-javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/home/circleci/repo/factcast-store-pgsql/target/jacoco.exec,excludes=**/*Configuration.*:**/*Application.*:**/*Exception.*:**/gen/*:**/generated/*' -jar /home/circleci/repo/factcast-store-pgsql/target/surefire/surefirebooter3558926134611331257.jar /home/circleci/repo/factcast-store-pgsql/target/surefire 2018-09-10T10-26-49_699-jvmRun1 surefire4240290956619915643tmp surefire_3656608706240041390tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] org.factcast.store.pgsql.internal.PGLatestSerialFetcher0Test
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/circleci/repo/factcast-store-pgsql && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java '-javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/home/circleci/repo/factcast-store-pgsql/target/jacoco.exec,excludes=**/*Configuration.*:**/*Application.*:**/*Exception.*:**/gen/*:**/generated/*' -jar /home/circleci/repo/factcast-store-pgsql/target/surefire/surefirebooter3558926134611331257.jar /home/circleci/repo/factcast-store-pgsql/target/surefire 2018-09-10T10-26-49_699-jvmRun1 surefire4240290956619915643tmp surefire_3656608706240041390tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 137
[ERROR] Crashed tests:
[ERROR] org.factcast.store.pgsql.internal.PGLatestSerialFetcher0Test
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :factcast-store-pgsql
Exited with code 1`

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-09-10 11:25:03 +0000 UTC_

also: happens with surefire, if i read this correctly.
