### ISSUE TITLE
Flaky test PgQueryTest.testRoundtripCatchupEventsInsertedAfterStart

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#628]
```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s - in org.factcast.store.pgsql.internal.PgFactIdToSerMapperTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PgQueryTest.testRoundtripCatchupEventsInsertedAfterStart:169 
factObserver.onNext(
    <any org.factcast.core.Fact>
);
Wanted 9 times:
-> at org.factcast.store.pgsql.internal.PgQueryTest.testRoundtripCatchupEventsInsertedAfterStart(PgQueryTest.java:169)
But was 8 times:
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
-> at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:154)
```

**Comment by uweschaefer** [comment]
funny, this worked so often as there is obviously no way to predict, when catchup is goind to happen due to the race condition.
