### ISSUE TITLE
Factcast CLI fails on publishing events

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#643]
**Describe the bug**
In order to be able to test a new factcast installation I want to use the factcast cli to publish test events.
This fails with the following exception

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.factcast.relocated.com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
        at org.factcast.relocated.com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at org.factcast.relocated.com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1357)
        at org.factcast.relocated.com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)
        at org.factcast.relocated.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1668)
        at org.factcast.relocated.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1235)
        at org.factcast.core.util.FactCastJson.readValue(FactCastJson.java:75)
        at org.factcast.core.DefaultFact.init(DefaultFact.java:90)
        at org.factcast.core.DefaultFact.<init>(DefaultFact.java:79)
        at org.factcast.core.DefaultFact.of(DefaultFact.java:72)
        at org.factcast.core.Fact.of(Fact.java:66)
        at org.factcast.client.grpc.cli.cmd.Publish.runWith(Publish.java:49)
        at org.factcast.client.grpc.cli.CLI.main(CLI.java:49)
        ... 8 more

```

I guess its related to a wrong use of [`asText()`](https://github.com/factcast/factcast/blob/master/factcast-core/src/main/java/org/factcast/core/util/FactCastJson.java#L119) because this is only useful for value nodes. If you have the following json as `jsonNode`
```
{"id":"1"}
```
`jsonNode.get("id").asText()` would be a valid call, but we want the entire node as text. 

**FactCast Server/Client Version**
Most recent (0.1.4.2)

**To Reproduce**
Inside factcast-client-grpc-cli execute (you must have a running factcast in the background)
`java -jar target/fc-cli.jar --no-tls publish --header test-header.json --payload test-payload.json`

**Expected behavior**
Should work :)

**Comment by uweschaefer** [comment]
thx @otbe
