### ISSUE TITLE
Unregister call from Eventbus fails unexpectedly

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#71]
_From @uweschaefer on 2018-07-03 10:50:05 +0000 UTC_

```
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is org.factcast.store.pgsql.internal.CondensedQueryExecutor@2ffb882d registered?
  at com.google.common.eventbus.EventBus.unregister(EventBus.java:230)
  at org.factcast.store.pgsql.internal.PGFactStream.close(PGFactStream.java:163)
  at org.factcast.core.subscription.SubscriptionImpl.close(SubscriptionImpl.java:50)
  at org.factcast.server.rest.resources.FactsObserver.unsubscribe(FactsObserver.java:160)
  at org.factcast.server.rest.resources.ConnectionCleanupRunnable.run(ConnectionCleanupRunnable.java:24)
  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.lang.Thread.run(Unknown Source)```

_Copied from original issue: Mercateo/factcast#71_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-07-23 13:23:19 +0000 UTC_

@ReneMazala unfortunately, the stacktrace is coming from an unknown build, so that i cannot exactly know what happens there. Assuming a double invocation of close() i did some precautionary measures. Let me know if it fixes the problem
