### ISSUE TITLE
cannot run Target:  org.factcast.server.grpc.TransportLayerException: null

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#72]
_From @StephanPraetsch on 2018-07-17 08:02:08 +0000 UTC_

I ran factcast locally and started a lightly adjusted SmokeMT
```
    @RequiredArgsConstructor
    @Component
    public static class MyFactCastRunner implements CommandLineRunner {

        @NonNull
        private final FactCast fc;

        @Override
        public void run(String... args) throws Exception {

            SmokeTestFact fact = new SmokeTestFact().type("foo").jsonPayload("{\"bla\":\"fasel\"}");
            fc.publish(fact);
            System.out.println("published " + fact);

            Optional<Fact> fetchById = fc.fetchById(fact.id());
            System.out.println("fetch by id " + fetchById.get().jsonPayload());

            Subscription sub = fc.subscribeToIds(
                    SubscriptionRequest.follow(FactSpec.ns("smoke")).fromScratch(),
                    f -> System.out.println(f))
                    .awaitCatchup(5000);

        }

    }
```

Anytime I saw this stacktrace in my local factcast
```
09:19:01 INFO  org.factcast.server.grpc.FactStoreGrpcService - subscribing grpc-sub#1 for 2d906fdd-f2aa-4030-a980-d81bc3583a08 (SmokeMT$SmokeMTCommandRunner.run:109) defined as {"maxBatchDelayInMs":0,"marks":true,"continuous":true,"ephemeral":false,"idOnly":true,"startingAfter":null,"debugInfo":"2d906fdd-f2aa-4030-a980-d81bc3583a08 (SmokeMT$SmokeMTCommandRunner.run:109)","specs":[{"ns":"smoke","type":null,"aggId":null,"jsFilterScript":null,"meta":{}}]}
09:19:01 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 connecting subscription {"maxBatchDelayInMs":0,"marks":true,"continuous":true,"ephemeral":false,"idOnly":true,"startingAfter":null,"debugInfo":"grpc-sub#1","specs":[{"ns":"smoke","type":null,"aggId":null,"jsFilterScript":null,"meta":{}}]}
09:19:01 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 catchup phase1 - historic facts staring with SER=0
09:19:01 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 catchup phase2 - facts since connect (SER=212196)
09:19:01 INFO  org.factcast.server.grpc.GrpcObserverAdapter - grpc-sub#1 onCatchup – sending catchup notification
09:19:01 INFO  org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 entering follow mode
09:19:01 DEBUG org.factcast.store.pgsql.internal.PGFactStream - registering org.factcast.store.pgsql.internal.CondensedQueryExecutor@dbb0560 for follow subscription
09:46:57 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 exception from subscription: null
09:46:57 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 disconnecting 
09:46:57 DEBUG org.factcast.store.pgsql.internal.PGFactStream - unregistering org.factcast.store.pgsql.internal.CondensedQueryExecutor@dbb0560 during close
09:46:57 DEBUG org.factcast.store.pgsql.internal.PGFactStream - grpc-sub#1 disconnected 
09:46:57 ERROR org.factcast.store.pgsql.internal.CondensedQueryExecutor - cannot run Target: 
org.factcast.server.grpc.TransportLayerException: null
	at org.factcast.server.grpc.BlockingStreamObserver.onNext(BlockingStreamObserver.java:68)
	at org.factcast.server.grpc.GrpcObserverAdapter.onNext(GrpcObserverAdapter.java:67)
	at org.factcast.server.grpc.GrpcObserverAdapter.onNext(GrpcObserverAdapter.java:1)
	at org.factcast.core.subscription.SubscriptionImpl.notifyElement(SubscriptionImpl.java:145)
	at org.factcast.store.pgsql.internal.PGFactStream$FactRowCallbackHandler.processRow(PGFactStream.java:193)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1580)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:703)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:690)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:747)
	at org.factcast.store.pgsql.internal.PGSynchronizedQuery$1.doInTransaction(PGSynchronizedQuery.java:84)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.factcast.store.pgsql.internal.PGSynchronizedQuery.run(PGSynchronizedQuery.java:79)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.runTarget(CondensedQueryExecutor.java:70)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.trigger(CondensedQueryExecutor.java:43)
	at org.factcast.store.pgsql.internal.CondensedQueryExecutor.onEvent(CondensedQueryExecutor.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34)
	at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

_Copied from original issue: Mercateo/factcast#72_

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-07-23 11:15:53 +0000 UTC_

cannot reproduce. any more information of how to reproduce would be helpful.

```2018-07-23 13:13:00.387  INFO 15523 --- [ault-executor-0] n.d.s.a.g.c.AddressChannelNameResolver   : Found gRPC server factstore localhost:9090
published org.factcast.example.grpc.SmokeTestFact@51a6cc2a
fetch by id {"bla": "fasel"}
67b0e422-514f-4acb-ae62-0c491419dc8a
577cf843-2873-42c5-b974-4f3503e303a5
519707f0-42e1-45f0-8546-aa011f91724f
e8e2eb8e-417a-4b97-873f-68052c6739ad```

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-07-23 11:19:16 +0000 UTC_

exception is server-side

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-07-23 12:42:34 +0000 UTC_

@StephanPraetsch please check if this fixes your issue

**Comment by uweschaefer** [comment]
_From @uweschaefer on 2018-07-23 13:25:06 +0000 UTC_

fixed
