### ISSUE TITLE
Add retryer for IO actions

### ISSUE THREAD

**Issue by Eszti** [factcast/factcast#894]
Sometimes due to connection errors an IO operation ends in a timeout. This raises an error like the following:

`org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:335)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy118.executeUpdate(Unknown Source)
	at org.factcast.store.pgsql.internal.catchup.PgCatchUpPrepare.lambda$prepareCatchup$0(PgCatchUpPrepare.java:58)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:646)
	at org.factcast.store.pgsql.internal.catchup.PgCatchUpPrepare.prepareCatchup(PgCatchUpPrepare.java:53)
	at org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup.run(PgPagedCatchup.java:81)
	at org.factcast.store.pgsql.internal.PgFactStream.catchup(PgFactStream.java:140)
	at org.factcast.store.pgsql.internal.PgFactStream.catchupAndFollow(PgFactStream.java:100)
	at org.factcast.store.pgsql.internal.PgFactStream.connect(PgFactStream.java:85)
	at org.factcast.store.pgsql.internal.PgSubscriptionFactory.lambda$subscribe$0(PgSubscriptionFactory.java:53)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)`

I suggest using a retryer for IO operations.
Alternatively, the timeout could also be increased.

**Comment by uweschaefer** [comment]
Thx for reporting. I know it is not easy with timeouts, but do you have any instructions of how to reproduce?

**Comment by Eszti** [comment]
We only got a logz.io notification. I'm not sure if we'll be able to figure it out what exactly triggered this error but we'll give it a try.

**Comment by uweschaefer** [comment]
If this is communication to the DB, wouldn't the usual spring boot properties work for you to tweak the timeout settings?

**Comment by uweschaefer** [comment]
feel free to reopen, if tweaking the DB settings does not work for you, or there is more input on how to reproduce it.
thanks.
